version: '3.6'
services:
  web:
    image: pycall-spacy-hang
    build:
      context: .
    ports:
      - '5555:5000'
    environment:
      OPENBLAS_NUM_THREADS: 1
      RACK_ENV: development
      APP_ENV: development
      PORT: 5000
    volumes:
      - '.:/srv/classifier'
